site_name: ProgramaciÃ³n en Java
nav:
    - ğŸ”¥ Inicio: index.md
    - ğŸ’¾ Elementos de un programa informÃ¡tico: 
      - ğŸ’¾ Programa y lenguajes de programaciÃ³n: ud1/1elementos.md
      - ğŸ’¾ El lenguaje Java:
        - Conceptos bÃ¡sicos del lenguaje: ud1/121conceptosbasicos.md
        - Setup: ud1/122setup.md
        - Proyecto Hola Mundo: ud1/123holamundo.md
      - ğŸ’¾ Variables, sentencias y paquetes:
        - Variables: ud1/131variables.md
        - Sentencias y paquetes: ud1/132sentencias.md
      - ğŸ’¾ Tipos de datos: 
        - Datos primitivos: ud1/14datatypejava.md
        - Datos no primitivos: ud1/142noprimitive.md
        - String: ud1/143string.md
      - ğŸ’¾ Operadores y expresiones: ud1/15operators.md
      - ğŸ’¾ Comentarios en Java: ud1/16comments.md
      - ğŸ’¾ Constantes y literales: ud1/17constantesliterales.md
      - ğŸ’¾ Entrada y salida de informaciÃ³n por consola: ud1/18inputoutputconsole.md
      - ğŸ’¾ IntroducciÃ³n a la programaciÃ³n orientada a objetos: ud1/19poo.md
    - ğŸ–²ï¸ Estructuras bÃ¡sicas de control:
      - ğŸ–²ï¸ Estructuras de selecciÃ³n: 
        - If Statement: ud2/1seleccion.md
        - Expresiones booleanas: ud2/11booleanexpressions.md
        - Switch Statement: ud2/2switch.md
      - ğŸ–²ï¸ Estructuras de repeticiÃ³n:
        - Bucle while: ud2/22while.md
        - Bucle do while: ud2/22dowhile.md
        - Bucles while con if: ud2/22whileif.md
        - Bucle for: ud2/22for.md
        - Bucles anidados: ud2/22nestedloop.md
        - Principios del diseÃ±o de bucles: ud2/22principlesloop.md
      - ğŸ–²ï¸ Estructuras de salto:
        - Sentencias break y continue: ud2/23breakcontinue.md
      - ğŸ–²ï¸ Control de excepciones: ud2/24exceptions.md
      - ğŸ–²ï¸ Prueba y depuraciÃ³n de aplicaciones: ud2/25fallos.md
      - ğŸ–²ï¸ IntroducciÃ³n a los mÃ©todos en Java: ud2/26methods.md 
    - â™¾ï¸ Recursividad: ud3/6recursion.md
    - ğŸŒ ProgramaciÃ³n orientada a objetos POO:
      - ğŸŒ Clases en Java: ud3/1metodoclase.md
      - ğŸŒ Constructores y destructores: ud3/2constructor.md
      - ğŸŒ MÃ©todos y sobrecarga de mÃ©todos: ud3/3sobrecargametodos.md
      - ğŸŒ Paso de parÃ¡metros por valor y referencia: ud3/4referencevalue.md
      - ğŸŒ Variables, mÃ©todos y clases estÃ¡ticas: ud3/5static.md
      - ğŸŒ Null value: ud3/7nullvalue.md
      - ğŸŒ POJO, Record: ud3/8pojo.md
    - ğŸ“… Arrays:
      - ğŸ“… IntroducciÃ³n: ud4/1arrays.md
      - ğŸ“… Algoritmos Ãºtiles en arrays: ud4/2usefularrays.md
      - ğŸ“… Tipos de referencia y tipos de valor: ud4/3referencetypearrays.md
      - ğŸ“… Array de objetos: ud4/4arrayobjects.md
      - ğŸ“… Algoritmos de ordenaciÃ³n: ud4/5sortarrays.md
      - ğŸ“… Algoritmos de bÃºsqueda: ud4/6searcharrays.md
      - ğŸ“… Arrays multidimensionales: ud4/7twodimensionarray.md
    - âœ¨ POO avanzada: 
      - âœ¨ Herencia: 
        - Concepto de herencia: ud5/1herencia.md
        - This vs super: ud5/1thisvssuper.md
      - âœ¨ ComposiciÃ³n: ud5/2composicion.md
      - âœ¨ EncapsulaciÃ³n: ud5/3encapsulacion.md
      - âœ¨ Polimorfismo: ud5/4polimorfismo.md
      - âœ¨ Interfaces: ud5/5interfaces.md
      - âœ¨ AbstracciÃ³n: ud5/6abstraccion.md
      - âœ¨ Excepciones: ud5/7exceptions.md
    - ğŸ§† Colecciones:
      - ğŸ§† List y ArrayList: ud6/1list.md
      - ğŸ§† Linked List: ud6/2linkedlist.md
      - ğŸ§† Clases Anidadas: ud6/3innerclass.md
      - ğŸ§† Map: ud6/4map.md
      - ğŸ§† Set: ud6/5set.md
      - ğŸ§† Colecciones ordenadas: ud6/6ordercollections.md
      - ğŸ§† Keyword Final: ud6/7final.md
      - ğŸ§† Equals & hashcode: ud6/8hashcode_equals.md 
    - ğŸ¦„ ProgramaciÃ³n avanzada:
      - ğŸ¦„ Keyword var: ud7/9var.md
      - ğŸ¦„ GenÃ©ricos: ud7/1generics.md
      - ğŸ¦„ Expresiones lambda: ud7/2lambda.md
      - ğŸ¦„ Predicate, Supplier and Consumer: ud7/3predicates.md
      - ğŸ¦„ Functions: ud7/4functions.md
      - ğŸ¦„ Referencia a mÃ©todos: ud7/5references.md
      - ğŸ¦„ Optional: ud7/8optional.md
      - ğŸ¦„ Streams: ud7/6streams.md
      - ğŸ¦„ Expresiones regulares: ud7/7regularexpressions.md
    - ğŸ¤© Interfaces de usuario:
      - ğŸ¤© Java FX: ud8/1javafx.md
      - ğŸ¤© Stage: ud8/2stage.md
      - ğŸ¤© Scene: ud8/3scene.md
      - ğŸ¤© Node: ud8/4node.md
      - ğŸ¤© Layouts: ud8/6layouts.md
      - ğŸ¤© Controles UI: ud8/5uicontrols.md
      - ğŸ¤© Eventos: ud8/7events.md
    - ğŸ“ Entrada/Salida (I/O) de la informaciÃ³n:
      - ğŸ“ Input/Output: ud9/1io.md
      - ğŸ“ Ficheros binarios: ud9/12binaryfiles.md
      - ğŸ“ Ficheros de caracteres: ud9/13characterfiles.md
      - ğŸ“ Clase File: ud9/14fileclass.md
      - ğŸ“ java.nio: ud9/15javanio.md
      - ğŸ“ Ficheros de acceso aleatorio: ud9/16randomaccessfile.md
      - ğŸ“ Ficheros de configuraciÃ³n: ud9/17configfiles.md
      - ğŸ“ XML: ud9/18xmlfiles.md
      - ğŸ“ JSON: ud9/19jsonfiles.md
      - ğŸ“ Crear un .jar: ud9/20createjar.md
      - ğŸ“ try-with-resources: ud9/21tryresources.md
    - ğŸ§  Persistencia de la informaciÃ³n:
      - ğŸ§  Persistencia: ud10/1persistence.md
      - ğŸ§  Desfase objeto-relacional: ud10/2mapeo.md
      - ğŸ§  Manejo de conectores - JDBC: ud10/3conectores.md
      - ğŸ§  Transacciones: ud10/4transactions.md
      - ğŸ§  Mejora del rendimiento: ud10/6rendimiento.md
      - ğŸ§  Estructura de los proyectos: ud10/7projectstructure.md
    - ğŸ”£ Atajos de teclado para IntelliJ: shortcuts.md
    - â¤ï¸â€ğŸ”¥ About me : about.md
theme:
  name: material
  language: es
  custom_dir: overrides
  #logo: assets/logo.png
  
  palette:
    - scheme: default
      primary: teal
      accent: "Teal"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo noche
    - scheme: slate
      primary: teal
      accent: "Teal"
      toggle:
        icon: material/toggle-switch
        name: Cambiar a modo dÃ­a
  
  extra:
    #generator: false
  
  copyright: Copyright &copy; 2021 - Patricia MartÃ­
  
  features:
    - content.code.annotate
    - navitagion.tabs
    #- navigation.sections
    - navigation.top

markdown_extensions:
  - admonition
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

extra:  
  analytics:
    provider: google
    property: G-FTWMZYNBPC